language: c

sudo: false

addons:
  apt:
    packages:
      - texlive-latex-recommended
      - texlive-latex-extra
      - latex-beamer

install:
  - mkdir bin
  - wget http://mirrors.ctan.org/support/latexmk/latexmk.pl
  - mv latexmk.pl bin/latexmk
  - chmod a+x bin/latexmk
  - export PATH=$PWD/bin:$PATH

env:
  - SUBDIR=beamer-lecture-notes
  - SUBDIR=advanced-bibliography

script:
  - cd $SUBDIR
  - make
