language: c

before_install:
  - sudo apt-add-repository -y ppa:grand-edgemaster/latex-backport
  - sudo apt-get update -qq
  - sudo apt-get install -y latexmk latex-beamer texlive-latex-recommended texlive-latex-extra

env:
  - SUBDIR=beamer-lecture-notes

script:
  - cd $SUBDIR
  - make
